name: Aseprite Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release]
        enable_ui: [on]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 下载Skia
          curl -L https://github.com/adaiblog/skia/releases/download/skia/skia.zip --output skia.zip
          7z x skia.zip

      - name: Configure CMake
        run: |
          cmake -S. -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DENABLE_UI=${{ matrix.enable_ui }} `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR=./skia `
            -DSKIA_LIBRARY_DIR=./skia/out/release-x64 `
            -DSKIA_LIBRARY=./skia/out/release-x64/skia.lib

      - name: Build Aseprite
        run: |
          cmake --build build

      - name: Package Aseprite
        uses: actions/upload-artifact@v4
        with:
          name: aseprite
          path: |
            build/bin/data
            build/bin/aseprite.exe
